// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_46L3_ZayboFrA0PSaPPT8YCmhlHhIG8',
    appId: '1:393022746976:web:d65db138a7c70509572e05',
    messagingSenderId: '393022746976',
    projectId: 'krishisetu-d4bcd',
    authDomain: 'krishisetu-d4bcd.firebaseapp.com',
    storageBucket: 'krishisetu-d4bcd.firebasestorage.app',
    measurementId: 'G-03RTEYW5NC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBft94vSDAM0gPRZPDzXHkcdCDQiTXq7Oc',
    appId: '1:393022746976:android:54538b5ce84997f9572e05',
    messagingSenderId: '393022746976',
    projectId: 'krishisetu-d4bcd',
    storageBucket: 'krishisetu-d4bcd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-Wt9H9DiReA7DnXu1RL5izBIjdm49fyU',
    appId: '1:393022746976:ios:1838452413fd49b4572e05',
    messagingSenderId: '393022746976',
    projectId: 'krishisetu-d4bcd',
    storageBucket: 'krishisetu-d4bcd.firebasestorage.app',
    iosBundleId: 'com.example.krishisetu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-Wt9H9DiReA7DnXu1RL5izBIjdm49fyU',
    appId: '1:393022746976:ios:1838452413fd49b4572e05',
    messagingSenderId: '393022746976',
    projectId: 'krishisetu-d4bcd',
    storageBucket: 'krishisetu-d4bcd.firebasestorage.app',
    iosBundleId: 'com.example.krishisetu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_46L3_ZayboFrA0PSaPPT8YCmhlHhIG8',
    appId: '1:393022746976:web:8009f0b3c7927baa572e05',
    messagingSenderId: '393022746976',
    projectId: 'krishisetu-d4bcd',
    authDomain: 'krishisetu-d4bcd.firebaseapp.com',
    storageBucket: 'krishisetu-d4bcd.firebasestorage.app',
    measurementId: 'G-9NC965FNY4',
  );
}
